version: '3.8'

services:
  # First vector store node
  node-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-mind-node-1
    environment:
      - NODE_ID=node-1
      - HTTP_PORT=8080
      - DIMENSIONS=128
      - DISTANCE_FUNCTION=cosine
      - LOG_LEVEL=info
    ports:
      - "8080:8080"
    volumes:
      - node1_data:/home/appuser/data
    networks:
      - tiny-raft-network
    restart: unless-stopped

  # Second vector store node (optional, for distributed setup)
  node-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-mind-node-2
    environment:
      - NODE_ID=node-2
      - HTTP_PORT=8081
      - DIMENSIONS=128
      - DISTANCE_FUNCTION=cosine
      - LOG_LEVEL=info
      - CLUSTER_NODES=node-1:8080
    ports:
      - "8081:8081"
    volumes:
      - node2_data:/home/appuser/data
    networks:
      - tiny-raft-network
    depends_on:
      - node-1
    restart: unless-stopped

  # Third vector store node (optional, for distributed setup)
  node-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-mind-node-3
    environment:
      - NODE_ID=node-3
      - HTTP_PORT=8082
      - DIMENSIONS=128
      - DISTANCE_FUNCTION=cosine
      - LOG_LEVEL=info
      - CLUSTER_NODES=node-1:8080,node-2:8081
    ports:
      - "8082:8082"
    volumes:
      - node3_data:/home/appuser/data
    networks:
      - tiny-raft-network
    depends_on:
      - node-1
      - node-2
    restart: unless-stopped

# Volumes for persisting data
volumes:
  node1_data:
  node2_data:
  node3_data:

# Network for inter-node communication
networks:
  nexus-mind-network:
    driver: bridge